dovtest: dovtest.cc
	g++ -I Devil/include -g dovtest.cc -o dovtest.exe -L . -lIL -lilu -lilut # -lfreeglut

#	g++ -I Devil/include -g dovtest.cc -o dovtest.exe -L DevIL/build/lib/x64/ -lIL -lilu -lilut # -lfreeglut

test2: test2.cc
	g++ -I Devil/include -g test2.cc -o test2.exe -L . -lIL -lilu -lilut # -lfreeglut
